import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'error': '#ffb4ab',
        'secondary-fixed': '#62fae3',
        'surface-container-low': '#1b1c1e',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-secondary-container': '#004d44',
        'on-surface-variant': '#bdc8d1',
        'on-primary': '#00354a',
        'surface-container-highest': '#343537',
        'outline-variant': '#3e484f',
        'secondary-fixed-dim': '#3cddc7',
        'surface-container-lowest': '#0d0e10',
        'on-primary-fixed': '#001e2c',
        'inverse-on-surface': '#303033',
        'secondary-container': '#03c6b2',
        'on-secondary': '#003731',
        'tertiary': '#ffc176',
        'surface': '#121315',
        'outline': '#87929a',
        'primary-fixed-dim': '#7bd0ff',
        'on-primary-container': '#004965',
        'inverse-primary': '#00668a',
        'secondary': '#44e2cd',
        'surface-container-high': '#292a2c',
        'inverse-surface': '#e3e2e5',
        'primary-container': '#38bdf8',
        'on-surface': '#e3e2e5',
        'on-primary-fixed-variant': '#004c69',
        'on-secondary-fixed': '#00201c',
        'tertiary-fixed': '#ffddb8',
        'surface-container': '#1f2022',
        'surface-tint': '#7bd0ff',
        'tertiary-container': '#f1a02b',
        'surface-bright': '#38393b',
        'on-tertiary-container': '#613b00',
        'on-tertiary': '#472a00',
        'on-tertiary-fixed-variant': '#653e00',
        'on-tertiary-fixed': '#2a1700',
        'primary': '#8ed5ff',
        'background': '#121315',
        'on-secondary-fixed-variant': '#005047',
        'tertiary-fixed-dim': '#ffb960',
        'surface-dim': '#121315',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#c4e7ff',
        'on-background': '#e3e2e5',
        'surface-variant': '#343537',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

export default config
